Do Not Merge
BlueSlug/handbook.floeproject.org pull request #2
Opened 2022-02-16 21:34 UTC by carenwatkins

updating semantics and expanding meaning. To be reviewed by Dana

2022-02-17 18:29 UTC, dayotte approved these changes

2022-02-17 18:34 UTC, dayotte approved these changes

2022-02-17 18:36 UTC, dayotte approved these changes

2022-02-17 18:38 UTC, dayotte requested changes
I think this should read "...inclusive learning and THE future of education"

2022-02-17 18:38 UTC, dayotte approved these changes

2022-02-17 18:51 UTC, carenwatkins commented
> I think this should read "...inclusive learning and THE future of education"

yes, agree. I stumbled on that as well. Has that change been made @dayotte ?

2022-02-17 20:49 UTC, dayotte approved these changes

2022-02-18 16:02 UTC, carenwatkins commented
@BlueSlug ready to merge

2022-02-18 18:27 UTC, merged